# Generated by Django 2.2.6 on 2019-11-16 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=105, unique=True)),
                ('plot_type', models.CharField(choices=[('Bar', 'Bar'), ('Stacked Bar', 'Stacked Bar'), ('Box', 'Box'), ('Geographical', 'Geographical'), ('Pie', 'Pie'), ('Scatter', 'Scatter'), ('Time Series', 'Time Series')], default='1', max_length=25)),
                ('default_settings', models.TextField(blank=True, max_length=750)),
                ('aggregation_type', models.CharField(blank=True, max_length=25)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='dataset.Dataset')),
            ],
            options={
                'verbose_name': 'Plot',
            },
        ),
    ]
